#!/bin/sh
# shell script to prepend i3status with more stuff

i3status | while :
do
        read line
	mem=$(grep MemAvail /proc/meminfo | awk '{printf "Mem %.01f GB", $2/2^20}')
        echo $mem" | "$line || exit 1
done

