#! /bin/sh

sudo systemctl start mysqld
sudo systemctl start sshd

~/installations/eclipse/eclipse &

xfce4-terminal -e msshdb &

ec

xset r rate 160 100

echo 524288 | sudo tee -a /proc/sys/fs/inotify/max_user_watches
