#! /bin/sh

echo 524288 | sudo tee -a /proc/sys/fs/inotify/max_user_watches

encfs ~/.enc/ ~/enc/ -- -o allow_other

sudo systemctl start mysqld
sudo systemctl start sshd

xfce4-terminal -e msshdb &

ec

xset r rate 160 100

