#! /bin/sh

echo 524288 | sudo tee -a /proc/sys/fs/inotify/max_user_watches

encfs ~/.enc/ ~/enc/ -- -o allow_other

sudo systemctl start mysqld
sudo systemctl start sshd

ec

xset r rate 160 100

sudo tlp start
sudo bluetooth off

xfce4-terminal -e msshdb &

sudo killall notify-osd
LOG=1 /usr/lib/notify-osd-customizable/notify-osd &

wingo --replace &

