#! /bin/sh
# basic initializations
#xmodmap ~/.Xmodmap
killall keynav
keynav
#xfce4-session &
#_xfce4-power-manager
#_sleep 5
wingo --replace &
#_xrdb merge ~/.Xresources
#_urxvt &
xset r rate 220 160

#sudo bluetooth off
#sudo tlp start

#sudo killall notify-osd
#LOG=1 /usr/lib/notify-osd-customizable/notify-osd &

