#! /bin/sh
# basic initializations
#xmodmap ~/.Xmodmap
keynav
#xfce4-session &
xfce4-power-manager
sleep 5
wingo --replace &
xrdb merge ~/.Xresources
urxvt &
xset r rate 220 160

sudo bluetooth off
sudo tlp start

sudo killall notify-osd
LOG=1 /usr/lib/notify-osd-customizable/notify-osd &

